### ISSUE TITLE
Urge to add topic:'hacktoberfest' to the repository

### ISSUE THREAD

**Issue by keivalya** [NvsYashwanth/Machine-Learning-Master#8]
An important update regarding HACKTOBERFEST:

```
PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)
```

From the link: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by NvsYashwanth** [comment]
> An important update regarding HACKTOBERFEST:
> 
> ```
> PRs count if:
> Submitted in a repo with the hacktoberfest topic AND
> during the month of October AND (
>   The PR is merged OR
>   The PR is labelled as hacktoberfest-accepted by a maintainer OR
>   The PR has been approved
> )
> ```
> 
> From the link: https://hacktoberfest.digitalocean.com/hacktoberfest-update

I see that you want to make your PRs count for the hacktober fest! @keivalya 
Sure. I'll add the label as well.
